# example netlify.toml
[build]
  command = "hugo"
  functions = "netlify/functions"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.101.0"
  CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"

[[plugins]]
  package = "netlify-plugin-cypress"

  [plugins.inputs.postBuild]
    enable = true
    wait-on-timeout = '30'

  [plugins.inputs]
    enable = false